from __future__ import annotations

import os
from typing import Any, Callable, Dict, Optional

from app.suggestion_generator import SuggestionGenerator
from .grok_client import GrokClient


class LLMSuggestionEngine:
    """Generates suggestions via OpenAI, local LLM, or template fallback."""

    def __init__(
        self,
        *,
        openai_client: Any | None = None,
        local_llm: Optional[Callable[[Dict[str, object]], Dict[str, object]]] = None,
    ) -> None:
        self.openai_client = openai_client
        self.local_llm = local_llm
        self.template_generator = SuggestionGenerator()
        self.grok_client = GrokClient(api_key_env="GENERATOR_GROK_API_KEY", model_env="GENERATOR_GROK_MODEL")

    def generate(self, context: Dict[str, object]) -> Dict[str, object]:
        grok_suggestion = self._generate_grok(context)
        if grok_suggestion is not None:
            return grok_suggestion

        if self.openai_client is not None and os.getenv("OPENAI_API_KEY", "").strip():
            suggestion = self._generate_openai(context)
            if suggestion is not None:
                return suggestion

        if self.local_llm is not None:
            try:
                suggestion = self.local_llm(context)
                if suggestion:
                    return suggestion
            except Exception:
                pass

        return self._generate_template(context)

    def _generate_grok(self, context: Dict[str, object]) -> Dict[str, object] | None:
        text = self.grok_client.complete_text(
            system_prompt=str(context.get("prompt_context", "")),
            user_prompt=(
                f"Task: {context.get('task', 'general_query')}\n"
                f"Language: {context.get('language', 'plain_text')}\n"
                f"Objective: {context.get('objective', '')}\n"
                f"Previous code:\n{context.get('previous_code', '')}"
            ),
        )
        if not text:
            return None
        return {
            "type": "response" if context.get("task") == "general_query" else "code",
            "language": context.get("language", "plain_text"),
            "content": text,
            "explanation": "Generated by Grok.",
            "provider": "grok",
        }

    def _generate_openai(self, context: Dict[str, object]) -> Dict[str, object] | None:
        try:
            response = self.openai_client.responses.create(  # type: ignore[attr-defined]
                model=os.getenv("OPENAI_MODEL", "gpt-4.1-mini"),
                input=[
                    {"role": "system", "content": context.get("prompt_context", "")},
                    {"role": "user", "content": context.get("objective", "")},
                ],
            )
            text = getattr(response, "output_text", "").strip()
            if not text:
                return None
            return {
                "type": "response" if context.get("task") == "general_query" else "code",
                "language": context.get("language", "plain_text"),
                "content": text,
                "explanation": "Generated by OpenAI provider.",
                "provider": "openai",
            }
        except Exception:
            return None

    def _generate_template(self, context: Dict[str, object]) -> Dict[str, object]:
        task = str(context.get("task", "general_query"))
        objective = str(context.get("objective", "")).strip()
        if task in {"general_query", "casual_conversation"}:
            return {
                "type": "response",
                "language": "plain_text",
                "content": self._general_response(objective),
                "explanation": self._general_response(objective),
                "provider": "template",
            }
        if task == "implementation_package":
            package = self._implementation_package(context)
            return {
                "type": "response",
                "language": str(context.get("language", "plain_text")),
                "content": package,
                "explanation": f"Generated the selected {context.get('strategy', 'recommended')} implementation package.",
                "provider": "template",
            }
        if context.get("clarification_state", {}).get("non_implementation"):
            design_response = self._design_response(objective)
            return {
                "type": "response",
                "language": "plain_text",
                "content": design_response,
                "explanation": design_response,
                "provider": "template",
            }
        if context.get("strategy"):
            strategy_response = self._strategy_response(context)
            return {
                "type": "response",
                "language": str(context.get("language", "plain_text")),
                "content": strategy_response,
                "explanation": self._strategy_explanation(context),
                "provider": "template",
            }
        user_intent = {
            "task": {
                "code_generation": "writing_new_code",
                "debugging": "debugging",
                "explanation": "exploring_api",
                "documentation": "exploring_api",
                "general_query": "casual_conversation",
            }.get(task, "writing_new_code")
        }
        generated = self.template_generator.generate(
            user_intent=user_intent,
            memory={
                "conversation_history": list(context.get("conversation_history", [])) + [{"role": "user", "content": context.get("objective", "")}],
                "code_memory": {
                    "language": context.get("language", "plain_text"),
                    "last_generated_code": context.get("previous_code", ""),
                },
            },
            task_context={"language": context.get("language", "plain_text")},
            user_preferences=context.get("user_preferences", {}),
            task_understanding={
                "active_task": {
                    "code_generation": "writing_new_code",
                    "debugging": "debugging_code",
                    "explanation": "asking_for_explanation",
                    "documentation": "asking_for_explanation",
                    "general_query": "casual_conversation",
                }.get(task, "writing_new_code"),
                "retrieved_code": context.get("previous_code", ""),
            },
        )
        suggestion_type = "response" if task == "general_query" else "code"
        if task == "debugging":
            suggestion_type = "debug_strategy"
        elif task in {"explanation", "documentation"}:
            suggestion_type = "explanation"
        return {
            "type": suggestion_type,
            "language": generated.get("language", context.get("language", "plain_text")),
            "content": generated.get("code", ""),
            "explanation": generated.get("explanation", "Generated by template fallback."),
            "provider": "template",
        }

    def _general_response(self, objective: str) -> str:
        lowered = objective.lower()
        if any(token in lowered for token in ["who are u", "who are you", "what are u", "what are you"]):
            return "I am the assistant in this terminal. I can chat normally, ask clarifying questions when a task is underspecified, and help with code, debugging, design, and explanations."
        if any(token in lowered for token in ["how are u", "how are you", "how r u"]):
            return "I am ready to help. Tell me what you want to build, fix, or understand, and I will continue."
        if "physics question" in lowered:
            return "Try this: A 2 kg object starts from rest and is pushed with a constant 6 N force for 5 seconds on a frictionless surface. What are its acceleration, final velocity, and displacement?"
        if any(token in lowered for token in ["hello", "hi", "hey"]):
            return "Hello. Tell me what you want to build, fix, or understand, and I will help."
        if lowered.endswith("?") or lowered.startswith(("what ", "why ", "how ", "when ", "where ", "who ")):
            return "I can answer normal questions and help with technical work. Ask directly, and if a build task is underspecified I will ask only the missing questions."
        return "I can help with coding tasks, debugging, design questions, and technical explanations. Tell me the specific task and I will continue."

    def _design_response(self, objective: str) -> str:
        return (
            f"I will treat this as a conceptual design task for: {objective}. "
            "I can outline the core idea, rules, user flow, components, and possible implementation paths without writing code yet."
        )

    def _strategy_explanation(self, context: Dict[str, object]) -> str:
        strategy = str(context.get("strategy", "recommended")).lower()
        if strategy == "simple":
            return "A minimal implementation focused on getting the feature working quickly."
        if strategy == "optimized":
            return "An implementation focused on cleaner abstractions, validation, and efficiency."
        if strategy == "scalable":
            return "A production-oriented architecture with clearer separation for future growth."
        return "A structured implementation option."

    def _strategy_response(self, context: Dict[str, object]) -> str:
        strategy = str(context.get("strategy", "simple")).lower()
        objective = str(context.get("objective", "")).strip() or "the requested task"
        language = str(context.get("language", "plain_text"))
        framework = str(context.get("framework") or "none")
        storage = str(context.get("storage") or "none")
        if strategy == "simple":
            return (
                f"Simple implementation for {objective}:\n"
                f"- Language: {language}\n"
                f"- Framework: {framework}\n"
                f"- Storage: {storage}\n"
                "- Approach: keep everything in one small service or file where practical.\n"
                "- Best for: prototypes and fast validation.\n"
                "- Starter shape: single entry point, one data model, one basic workflow."
            )
        if strategy == "optimized":
            return (
                f"Optimized implementation for {objective}:\n"
                f"- Language: {language}\n"
                f"- Framework: {framework}\n"
                f"- Storage: {storage}\n"
                "- Approach: split logic into clear layers, add validation, and reduce duplicated work.\n"
                "- Best for: maintainable mid-size projects.\n"
                "- Starter shape: controller or handler layer, service layer, persistence layer, validation utilities."
            )
        return (
            f"Scalable architecture for {objective}:\n"
            f"- Language: {language}\n"
            f"- Framework: {framework}\n"
            f"- Storage: {storage}\n"
            "- Approach: define modules, contracts, and boundaries so more features can be added safely.\n"
            "- Best for: production systems and growing teams.\n"
            "- Starter shape: domain modules, API layer, service layer, repository layer, config, and tests."
        )

    def _implementation_package(self, context: Dict[str, object]) -> str:
        strategy = str(context.get("strategy", "recommended")).title()
        objective = str(context.get("objective", "")).strip() or "Requested system"
        language = str(context.get("language", "plain_text"))
        framework = str(context.get("framework") or "none")
        storage = str(context.get("storage") or "none")
        starter_code = self._starter_code(language, framework)
        return (
            f"Implementation Plan\n"
            f"Task: {objective}\n"
            f"Selected Strategy: {strategy}\n\n"
            f"System Architecture\n"
            f"- Language: {language}\n"
            f"- Framework: {framework}\n"
            f"- Database: {storage}\n"
            f"- Runtime shape: {'modular service-based structure' if strategy.lower() == 'scalable' else 'single application structure'}\n\n"
            "Project Structure\n"
            "- src/\n"
            "- src/controllers/\n"
            "- src/services/\n"
            "- src/models/\n"
            "- src/config/\n"
            "- tests/\n\n"
            f"Starter Code\n{starter_code}"
        )

    def _starter_code(self, language: str, framework: str) -> str:
        if language == "java" and framework.lower() in {"spring boot", "spring"}:
            return (
                "```java\n"
                "@SpringBootApplication\n"
                "public class App {\n"
                "    public static void main(String[] args) {\n"
                "        SpringApplication.run(App.class, args);\n"
                "    }\n"
                "}\n"
                "```"
            )
        if language == "python":
            return (
                "```python\n"
                "def main() -> None:\n"
                "    print('Starter application ready')\n\n"
                "if __name__ == '__main__':\n"
                "    main()\n"
                "```"
            )
        if language == "javascript":
            return (
                "```javascript\n"
                "function main() {\n"
                "  console.log('Starter application ready');\n"
                "}\n\n"
                "main();\n"
                "```"
            )
        return (
            "```text\n"
            "Starter application ready.\n"
            "Add your first entry point, domain model, and main workflow here.\n"
            "```"
        )
