from __future__ import annotations

import os
from typing import Any, Callable, Dict, Optional

from app.suggestion_generator import SuggestionGenerator


class LLMSuggestionEngine:
    """Generates suggestions using OpenAI/local callbacks with template fallback."""

    def __init__(
        self,
        *,
        openai_client: Any | None = None,
        local_llm: Optional[Callable[[Dict[str, object]], Dict[str, object]]] = None,
    ) -> None:
        self.openai_client = openai_client
        self.local_llm = local_llm
        self.template_generator = SuggestionGenerator()

    def generate_suggestion(self, context: Dict[str, object]) -> Dict[str, object]:
        if self.openai_client is not None and os.getenv("OPENAI_API_KEY", "").strip():
            suggestion = self._generate_openai(context)
            if suggestion is not None:
                return suggestion

        if self.local_llm is not None:
            try:
                suggestion = self.local_llm(context)
                if suggestion:
                    return suggestion
            except Exception:
                pass

        return self._generate_template(context)

    def _generate_openai(self, context: Dict[str, object]) -> Dict[str, object] | None:
        try:
            response = self.openai_client.responses.create(  # type: ignore[attr-defined]
                model=os.getenv("OPENAI_MODEL", "gpt-4.1-mini"),
                input=[
                    {"role": "system", "content": context.get("system_prompt", "")},
                    {"role": "user", "content": context.get("task", {}).get("raw_input", "")},
                ],
            )
            text = getattr(response, "output_text", "").strip()
            if not text:
                return None
            return {
                "type": "code" if context.get("task", {}).get("task_type") != "general_query" else "response",
                "language": context.get("language", "plain_text"),
                "content": text,
                "explanation": "Generated by OpenAI model.",
                "provider": "openai",
            }
        except Exception:
            return None

    def _generate_template(self, context: Dict[str, object]) -> Dict[str, object]:
        task = dict(context.get("task", {}))
        user_intent = {
            "task": {
                "code_generation": "writing_new_code",
                "debugging": "debugging",
                "explanation": "exploring_api",
                "general_query": "exploring_api",
            }.get(task.get("task_type", "general_query"), "writing_new_code")
        }
        generated = self.template_generator.generate(
            user_intent=user_intent,
            memory={
                "conversation_history": context.get("conversation_context", []) + [{"role": "user", "content": task.get("raw_input", "")}],
                "code_memory": {
                    "language": context.get("language", "plain_text"),
                    "last_generated_code": context.get("previous_code", ""),
                },
            },
            task_context={"language": context.get("language", "plain_text")},
            user_preferences=context.get("user_preferences", {}),
            task_understanding={
                "active_task": {
                    "code_generation": "writing_new_code",
                    "debugging": "debugging_code",
                    "explanation": "asking_for_explanation",
                    "general_query": "casual_conversation",
                }.get(task.get("task_type", "general_query"), "writing_new_code"),
                "retrieved_code": context.get("previous_code", ""),
            },
        )
        suggestion_type = "response" if task.get("task_type") == "general_query" else "code"
        if task.get("task_type") == "debugging":
            suggestion_type = "debug_strategy"
        elif task.get("task_type") == "explanation":
            suggestion_type = "explanation"
        return {
            "type": suggestion_type,
            "language": generated.get("language", context.get("language", "plain_text")),
            "content": generated.get("code", ""),
            "explanation": generated.get("explanation", "Generated by template fallback."),
            "provider": "template",
        }
